#!/usr/bin/env Rscript

################################################
############### IMPORT LIBRARIES ###############
################################################

library("optparse")

option_list = list(
  make_option(c("-f", "--file"), type="character", default=NULL, 
              help="dataset file name", metavar="character"),
  make_option(c("-c", "--chr"), type="character", default="no_chr_specified", 
              help="chromosome name", metavar="character"),
  make_option(c("-o", "--out"), type="character", default="out.txt", 
              help="output file name [default= %default]", metavar="character"));
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$file)){
  print_help(opt_parser)
  stop("Missing input file (generated by LDhat stat)", call.=FALSE)
}

if (is.null(opt$out)){
  print_help(opt_parser)
  stop("Missing output file name", call.=FALSE)
}


################################################
############### FORMAT THE TABLE ###############
################################################

res <- read.table(opt$file, header = TRUE) # read in res table
res <- res[-1,] # delete the row with the overall stats

Ne <- 30353 # from http://www.ncbi.nlm.nih.gov/pubmed/25874894

cm <- cumsum(res$Mean_rho*(100/(2*Ne)))
chromosome <- rep(opt$chr, length(cm))
locus <-paste(rep("locus", length(cm)), seq(from = 1, to = length(cm)), sep = "")
location <- res$Loci*1000

a_matrix <- cbind(chromosome, locus, cm, location)

### CONSTRUCT A PSEUDO FINAL LINE
### When the res.txt file is calculated by LDhat stat, 
### it loses a row of data and thus the map file is one row short.
### But selscan --ihs flips out when the number of loci in 
### the VCF file is 1 more than the nubmer of entries in the MAP file.
### So construct a pseudo final line for the MAP file that's just averages

final_line <- c(opt$chr, 
                paste("locus", length(cm)+1, sep = ""),
                tail(cm, 1) + tail(res$Mean_rho*(100/(2*Ne)), 1),
                round(tail(location, 1) + mean(diff(location))))

a_matrix <- rbind(a_matrix, final_line)

write.table(a_matrix, file = opt$out, quote = FALSE, row.names = FALSE, col.names = FALSE)


